#!/bin/dash

#check if pushy is initialized
if [ ! -d ".pushy" ] 
then
    echo "pushy-log: error: pushy repository directory .pushy not found"
    exit 1
fi

#check correct input
if [ $# -ne 0 ]
then
    echo "usage: pushy-log"
    exit 1
fi

cat ".pushy/log"